# Generated by Django 3.1.4 on 2021-02-19 01:26

import Plataforma.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, max_length=50, verbose_name='Creado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activ', models.CharField(choices=[('Actividad_Uno', 'Actividad Uno'), ('Actividad_Dos', 'Actividad Dos'), ('Actividad_Tres', 'Actividad Tres'), ('Actividad_Cuatro', 'Actividad Cuatro'), ('Actividad_Cinco', 'Actividad Cinco')], max_length=20, verbose_name='Actividad')),
                ('comentario', models.CharField(max_length=500, verbose_name='Comentario')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creacion')),
                ('archivo', models.FileField(upload_to=Plataforma.models.pathArchivo)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
